### ISSUE TITLE
REFACTR.TECH reschedule

### ISSUE THREAD

**Issue by laingbeth** [conferenceradar/list#130]
{
  "name": "REFACTR.TECH",
  "url": " https://www.refactr.tech/",
  "twitter": "https://twitter.com/RefactrTech",
  "city": "Atlanta",
  "stateProvince": "GA",
  "country": "USA",
  "eventStartDate": "2001-04-22T04:00:00.000Z",
  "eventEndDate": "2001-04-24T04:00:00.000Z",
  "status": "postponed",
  "statusUrl": "https://medium.com/@RefactrTech/covid-19-updates-for-refactr-tech-2020-72a1d8c9494a",
  "industry": "tech",
  "codeOfConduct": "",
  "latitude": 33.7489954,
  "longitude": -84.3879824
}

**Comment by ryanlanciaux** [comment]
Thank you - this has been added to the site.
