### ISSUE TITLE
Feature Request: Allow virtual-only events

### ISSUE THREAD

**Issue by sadukie** [conferenceradar/list#133]
With the events that are getting cancelled, there are virtual events that are sprouting up, as people see the need to replace these.  It would be nice if we could add virtual-only events.

Maybe the form looks like this:
![image](https://user-images.githubusercontent.com/106202/76522359-e15ceb80-643c-11ea-8854-98579de01628.png)

And if the checkbox is checked, don't validate City, State, or Country.

**Comment by ryanlanciaux** [comment]
Thanks for adding this and following up - sorry I've kind of let this project fall into disrepair 🙃 It was a very good idea.
