### ISSUE TITLE
WebExpo Prague

### ISSUE THREAD

**Issue by kjakobson** [conferenceradar/list#28]
Hi, this is the prime Prague conference about anything related to web development/design.

{
  "name": "WebExpo",
  "topic": "Explore the unforgettable city of Prague, listen to talks from more than 70 local and international speakers on many exciting topics, meet over 2000 web enthusiasts from many different countries and professions and enjoy the parties!",
  "url": "https://www.webexpo.cz/",
  "twitter": "https://twitter.com/webexpo?lang=cs",
  "city": "Prague",
  "stateProvince": "",
  "country": "Czech Republic",
  "eventStartDate": "2017-09-21T22:00:00.000Z",
  "eventEndDate": "2017-09-22T22:00:00.000Z",
  "cfpStartDate": "",
  "cfpEndDate": "",
  "codeOfConduct": ""
}

**Comment by ryanlanciaux** [comment]
Thanks a ton for adding this!
