### ISSUE TITLE
PR enquiry

### ISSUE THREAD

**Issue by Matslande** [conferenceradar/list#35]
{
  "name": "Webdagene",
  "topic": "Scandinavia’s biggest digital customer experience conference!",
  "url": "https://www.webdagene.no/",
  "twitter": "",
  "city": "Oslo",
  "stateProvince": "Oslo",
  "country": "Norway",
  "eventStartDate": "2017-10-17T22:00:00.000Z",
  "eventEndDate": "2017-10-19T22:00:00.000Z",
  "cfpStartDate": "",
  "cfpEndDate": "",
  "codeOfConduct": ""
}

**Comment by ryanlanciaux** [comment]
Thank you 👍  this has been added to the site.
