### ISSUE TITLE
Add State of the Map US

### ISSUE THREAD

**Issue by brightrain** [conferenceradar/list#36]
{
  "name": "State of the Map US",
  "topic": "Open Street Map US conference",
  "url": "https://2017.stateofthemap.us/",
  "twitter": "@sotmus",
  "city": "Boulder",
  "stateProvince": "CO",
  "country": "US",
  "eventStartDate": "2017-10-20T06:00:00.000Z",
  "eventEndDate": "2017-10-22T06:00:00.000Z",
  "cfpStartDate": "",
  "cfpEndDate": "",
  "codeOfConduct": "http://confcodeofconduct.com/"
}

**Comment by ryanlanciaux** [comment]
Thank you -- this has been added to the site.
