### ISSUE TITLE
Make event form generate json object

### ISSUE THREAD

**Issue by ryanlanciaux** [conferenceradar/list#56]
Form should generate json file with name based on provided data. Right now, the json data is placed in the text area next to the form. It would be good to have a button that exports the downloadable JSON file ("save as...")

**Comment by PSalant726** [comment]
Hi @ryanlanciaux - I took a crack at this in PR #68 

Let me know what you think!

**Comment by ryanlanciaux** [comment]
Awesome thanks so much! Will take a look at this today 👍
