### ISSUE TITLE
Switch to Gatsby

### ISSUE THREAD

**Issue by ryanlanciaux** [conferenceradar/list#61]
[Gatsby](https://github.com/gatsbyjs/gatsby) would make some of the long-term goals a little bit easier (plus Gatsby is awesome). Before any of the more sophisticated ideas get added, switch the site container to [Gatsby](https://github.com/gatsbyjs/gatsby)

**Comment by Klowner** [comment]
Is there example data somewhere? `src/data` doesn't exist.

**Comment by ryanlanciaux** [comment]
No worries :D I think we need to make some updates on the documentation because we used to have just one json file that all PRs were against rather than the merged file.

**Comment by SaraVieira** [comment]
Hello @ryanlanciaux

What are your long term goals for the website?

**Comment by ryanlanciaux** [comment]
Hi there! Well - a couple things -- right now mostly getting more data but eventually want to have a route for each conference. 

Longer term, I want to start pushing the conferences into a database upon build. The site should still have the same flow for now as far as maintenance is concerned where each conference is added through github. The database would be for more advanced features -- I want people to have the ability to say "As a speaker, here are the conferences I've submitted to, here are the ones my friends submitted to" and so on.

Right now we have some made-up "lookup" tables for storing a list of conferences as part of the URL (which these URLs are kind of ugly) but I think having a database would be nicer for that side of things. The main view would still load the static files -- database would just be for doing more custom views of the data.
